### ISSUE TITLE
pending suggestions from Debian

### ISSUE THREAD

**Issue by asarhaddon** [AdaCore/contributing-howto#4]
(in a private mail, Fabien Chouteau suggested this repository for such issues)
Hello.

A merge request is causing non-trivial rebase work for the third time in a year. The request is intrusive, and may very well be rejected in the end.  Could you please ensure that the review happens before new commits cause merge conflicts?

For unrelated reasons, the history lies in three github pull requests.
The original request (mixing unrelated subjects): https://github.com/AdaCore/gprbuild/pull/64
A separate request for linker.xml: https://github.com/AdaCore/gprbuild/pull/67
New request on gprconfig_kb repository: https://github.com/AdaCore/gprconfig_kb/pull/3

During previous rebase sessions, I had the feeling that the commit author would be more efficient, at least because they are in a position to test the changes on the targeted hardware.

**Comment by Fabien-Chouteau** [comment]
Thanks @asarhaddon I will make sure we make progress on this. See my answer on the issue: https://github.com/AdaCore/gprconfig_kb/pull/3
